[package]
name = "config"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Disallow unknown keys in configuration
strict = []
default = ["strict"]

[dependencies]
util = { path = "../../crates/util" }
schema = { path = "../schema" }
process_utils = { path = "../../crates/process_utils" }

tokio = { version = "1", default_features = false, features = ["fs"] }
serde = { version = "1", features = ["derive"] }
serde-aux = "4"

tracing = { version = "0.1", default_features = false }
hex = "0.4.2"
num_cpus = "1.13"
aes = "0.8"
sha1 = "0.10.5"
hmac = "0.12.1"
thiserror = "1"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
paste = "1"

serde_json = "1"
toml = { version = "0.5", features = ["preserve_order"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
