[general]
server_name = "Lantern Chat"
service_uuid = "8205afcb-e4a9-4769-81d9-c7c5f6edb4d7"
instance_id = 0
worker_id = 0
memory_limit = 0
cpu_limit = 0

[paths]
data_path = ""
cert_path = ""
key_path = ""
web_path = "./frontend"

[db]
db_str = "postgresql://postgres:password@localhost:5432"
migrations = "./sql/migrations"

[account]
session_duration = 7776000
min_age = 13
password_len = [8, 9999]
username_len = [3, 64]

[message]
max_newlines = 80
message_len = [1, 2500]
premium_message_len = [1, 5000]

[party]
partyname_len = [3, 64]
roomname_len = [3, 64]

[upload]
max_upload_size = 2147483647
max_upload_chunk_size = 8388608
monthly_upload_quota = 1073741824
monthly_premium_upload_quota = 6442450944
max_avatar_size = 4194304
max_banner_size = 8388608
avatar_width = 256
banner_width = 1600
banner_height = 900
max_avatar_pixels = 1048576
max_banner_pixels = 3686400

[upload.avatar_formats]
png = [100]
jpeg = [92, 70, 45]
avif = [95, 80]
gif = [100]
webm = [95]

[upload.banner_formats]
png = [100]
jpeg = [92, 70, 45]
avif = [90]
gif = [95]
webm = [95]

[services]
hcaptcha_secret = "0x0000000000000000000000000000000000000000"
hcaptcha_sitekey = "10000000-ffff-ffff-ffff-000000000001"
b2_app = ""
b2_key = ""

[keys]
file_key = "03bc8b35afaaf43eaed1f2337a5b89cde001211071bd73415c1f6fb0b50b7695"
mfa_key = "705061f519cfa1fedd96b27ff6732bd599d6b484c42ac48d0871b80cf228137f"
sf_key = "f8c6fe912b0e65cfecabae0ad78e7c2d"
bt_key = "4fc7a51480b0cabdb00b38335ab349394618915c69e1290d74766d875a0d3474340f4fee5463715ecc3f4a53b5562fa93338a963fab9900737ed90f7daf68457"

[web]
bind = "127.0.0.1:8080"
cdn_domain = "cdn.lanternchat.net"
strict_cdn = true
base_domain = "lantern.chat"
secure = true
