[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../../crates/db" }
util = { path = "../../crates/util" }
metrics = { path = "../../crates/metrics" }
totp = { path = "../../crates/totp" }
processing = { path = "../../crates/processing" }
iplist = { path = "../../crates/iplist" }
embed_parser = { path = "../../crates/embed_parser" }
blurhash = { path = "../../crates/blurhash" }
task_runner = { path = "../../crates/task_runner" }
filesystem = { path = "../../crates/filesystem" }

schema = { path = "../schema" }
config = { path = "../config" }

sdk = { git = "https://github.com/Lantern-chat/client-sdk-rs", features = ["pg", "api"], package = "client-sdk" }
smol_str = { version = "0.1", features = ["serde", "pg"] }

ftl = { git = "https://github.com/Lantern-chat/ftl", features = ["json", "cbor"] }
mime_db = { git = "https://github.com/Lantern-chat/mime_db" }
thorn = { git = "https://github.com/Lantern-chat/thorn" }
async-chashmap = { git = "https://github.com/novacrazy/async-chashmap" }

timestamp = { package = "iso8601-timestamp", version = "0.1", features = ["pg"] }

tokio = { version = "1", features = ["sync"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tracing = { version = "0.1", default-features = false, features = ["log", "std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.64"
ciborium = "0.2"
thiserror = "1"
futures = "0.3"
reqwest = { version = "0.11", default-features = false, features = ["gzip", "deflate", "brotli", "rustls-tls"] }
headers = "0.3"
rust-argon2 = "1"
base64 = "0.13.0"
memchr = "2.4.1"
mime = "0.3.16"
smallvec = "1.7.0"
num_cpus = "1.13"
hashbrown = { version = "0.12", features = ["inline-more"] }
time = { version = "0.3", features = ["macros"] }
lazy_static = "1.4.0"
regex = "1.4.6"
aes-gcm-siv = "0.10.3"
miniz_oxide = "0.5"
rand = "0.8.3"
base32 = "0.4.0"
arrayvec = "0.7.1"
aho-corasick = "0.7"
paste = "1.0.5"
bytecount = "0.6.2"