name = "camo"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"
send_metrics = false

route = { pattern = "cdn.lanternchat.net/camo/*", zone_name = "lanternchat.net" }

[vars]
WORKERS_RS_VERSION = "0.0.12"

[build]
command = "worker-build --release -- --no-default-features --features cf --config profile.release.opt-level='s'"

[env]
CAMO_SIGNING_KEY = "your_hexadecimal_signing_key"