[package]
name = "lantern"
version = "0.1.0"
authors = ["Novapone <fpnova@pm.me>"]
edition = "2018"
publish = false

[dependencies]
warp = { version = "0.3.0", features = ["compression"] }
tokio = { version = "1.0.1", features = ["full"] }
hashbrown = { version = "0.9.1", features = ["inline-more"] }
tokio-postgres = { version = "0.7.0", features = ["with-uuid-0_8", "with-chrono-0_4", "with-serde_json-1", "with-time-0_2"] }
chrono = "0.4.19"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
uuid = "0.8.1"
env = "0.0.0"
futures = "0.3.8"
tracing = { version = "0.1.22", default-features = false, features = ["log", "std"] }
tracing-futures = { version = "0.2.4", default-features = false, features = ["std-future"] }
tracing-subscriber = "0.2.15"
structopt = "0.3.21"
bytes = "1.0.0"
async-trait = "0.1.42"
anyhow = "1.0.37"
thiserror = "1.0.23"
dotenv = "0.15.0"
lru = "0.6.3"
ahash = "0.7"
serde_repr = "0.1.6"
paste = "1.0.4"
rmp-serde = "0.15.0"
tokio-stream = "0.1.0"
parking_lot = "0.11.1"
async-stream = "0.3.0"
arc-swap = "1.2.0"
# chacha20 = "0.6.0"
ctr = "0.6.0"
aes = "0.6.0"
regex = "1.4.3"
lazy_static = "1.4.0"
failsafe = "1.0.0"
rust-argon2 = "0.8.3"
time = "0.2.24"
rand = "0.8.2"
rand_chacha = "0.3.0"
base64 = "0.13.0"
postage = "0.4.1"
validator = { version = "0.12", features = ["derive"] }

[dependencies.flate2]
version = "1.0.19"
features = ["rust_backend"]
default-features = false

[build-dependencies]
built = { version = "0.4.4", features = ["git2", "chrono"] }

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "encrypt"
harness = false
