[patch.crates-io]
headers = { git = "https://github.com/Lantern-chat/headers" }
smol_str = { git = "https://github.com/Lantern-chat/smol_str", branch = "0.2" }
thin-vec = { git = "https://github.com/Lantern-chat/thin-vec" }
failsafe = { git = "https://github.com/Lantern-chat/failsafe-rs" }
iso8601-timestamp = { git = "https://github.com/Lantern-chat/iso8601-timestamp" }

# Contains fixes for nightly
# rand = { git = "https://github.com/rust-random/rand" }
# rand_core = { git = "https://github.com/rust-random/rand" }
# rand_chacha = { git = "https://github.com/rust-random/rand" }

# contains unpublished dependency bumps
# postgres-protocol = { git = "https://github.com/sfackler/rust-postgres" }
# postgres-types = { git = "https://github.com/sfackler/rust-postgres" }
# tokio-postgres = { git = "https://github.com/sfackler/rust-postgres" }
# postgres-derive = { git = "https://github.com/sfackler/rust-postgres" }

# postgres-inet = { git = "https://github.com/Lantern-chat/postgres-inet" }

[patch."https://github.com/Lantern-chat/client-sdk-rs"]
client-sdk-common = { path = "../client-sdk-rs/common" }
client-sdk = { path = "../client-sdk-rs" }

[workspace]
resolver = "2"
members = ["crates/*", "bin/*", "layers/*", "edge/*"]
# exclude = ["edge/embed-worker", "edge/camo"]

[profile.dev]
opt-level = 1
lto = 'thin'
incremental = false

[profile.release]
opt-level = 3
lto = 'fat'
codegen-units = 1

[profile.dev.build-override]
opt-level = 3

[profile.dev.package."*"]
codegen-units = 1
opt-level = 3
