[patch.crates-io]
headers = { git = "https://github.com/Lantern-chat/headers" }
smol_str = { git = "https://github.com/Lantern-chat/smol_str" }
failsafe = { git = "https://github.com/Lantern-chat/failsafe-rs" }
crc32fast = { git = "https://github.com/Lantern-chat/rust-crc32fast" }
# postgres-inet = { git = "https://github.com/Lantern-chat/postgres-inet" }


[workspace]
members = ["crates/*"]

[profile.dev]
opt-level = 1
lto = false

[profile.release]
opt-level = 3
lto = 'fat'
codegen-units = 1

[profile.dev.build-override]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3