[package]
name = "lantern"
version = "0.1.0"
authors = ["Novapone <fpnova@pm.me>"]
edition = "2018"
publish = false

[dependencies]
tokio = { version = "1.2", features = ["full"] }
hashbrown = { version = "0.11", features = ["inline-more"] }
tokio-postgres = { version = "0.7.0", features = ["with-uuid-0_8", "with-chrono-0_4", "with-serde_json-1", "with-time-0_2"] }
flate2 = { version = "1.0.19", default-features = false, features = ["rust_backend"] }
chrono = "0.4.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = "0.8"
env = "0.0.0"
futures = "0.3"
tracing = { version = "0.1", default-features = false, features = ["log", "std"] }
tracing-futures = { version = "0.2.4", default-features = false, features = ["std-future"] }
tracing-subscriber = "0.2.15"
structopt = "0.3.21"
bytes = "1.0"
async-trait = "0.1.42"
anyhow = "1"
thiserror = "1.0.23"
dotenv = "0.15.0"
lru = "0.6"
ahash = "0.7"
serde_repr = "0.1.6"
paste = "1.0.4"
rmp-serde = "0.15"
tokio-stream = "0.1"
parking_lot = "0.11.1"
async-stream = "0.3.0"
arc-swap = "1.2.0"
# chacha20 = "0.6.0"
ctr = "0.6.0"
aes = "0.6.0"
sha3 = "0.9.1"
regex = "1.4.3"
lazy_static = "1.4.0"
failsafe = "1.0.0"
rust-argon2 = "0.8.3"
time = { version = "0.2", features = ["serde"] }
rand = "0.8"
rand_chacha = "0.3.0"
base64 = "0.13.0"
hex = "0.4.2"
postage = "0.4.1"
# validator = { version = "0.12", features = ["derive"] }
hyper = { version = "0.14.4", features = ["http1", "http2", "server", "stream", "runtime"] }
tokio-tungstenite = "0.14.0"
http = "0.2.3"
async-compression = { version = "0.3.7", features = ["brotli", "deflate", "gzip", "tokio"] }
multipart = { version = "0.17", default-features = false, features = ["server"] }
serde_urlencoded = "0.7"
percent-encoding = "2.1"
mime = "0.3.16"
mime_guess = "2.0.3"
headers = "0.3"
url = "2.2.0"
tokio-util = { version = "0.6", features = ["io"] }
crc32fast = "1.2.1"
serde_shims = { version = "0.2", features = ["std", "mime", "bitflags"] }
bitflags = "1.2"
num_cpus = "1.13.0"
miniz_oxide = "0.4.4"

[build-dependencies]
built = { version = "0.4.4", features = ["git2", "chrono"] }
