[package]
name = "lantern"
version = "0.1.0"
authors = ["Nova <fpnova@pm.me>"]
edition = "2018"
publish = false

[dependencies]
warp = { version = "0.2.5", features = ["compression"] }
tokio = { version = "0.3.5", features = ["full"] }
hashbrown = "0.9.1"
tokio-postgres = { version = "0.6.0", features = ["with-uuid-0_8", "with-chrono-0_4", "with-serde_json-1"] }
chrono = "0.4.19"
serde = "1.0.118"
serde_json = "1.0.60"
uuid = "0.8.1"
