[package]
name = "regex_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
build = ["dep:regex-automata"]

[dependencies]
regex-automata = { optional = true, version = "0.1.10", features = ["std"] }
