[package]
name = "iplist"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnet = "2.3.1"
hashbrown = { version = "0.11", features = ["raw", "inline-more"] }