[package]
name = "embed-worker"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
reqwest = { version = "0.11", default_features = false, features = ["rustls-tls", "json", "gzip", "brotli", "deflate"] }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.6", features = ["http2"] }

embed_parser = { path = "../../crates/embed_parser", default_features = false }
md_utils = { path = "../../crates/md_utils" }
client-sdk = { path = "../../../client-sdk-rs", default_features = false }

hashbrown = { version = "0.13", features = ["inline-more", "serde"] }
iso8601-timestamp = "0.2"
imagesize = "0.12.0"
base64 = "0.21"
hmac = "0.12.1"
sha1 = "0.10.5"
hex = "0.4.3"
thiserror = "1"
dotenv = "0.15"
futures-util = "0.3.25"
memchr = "2.5.0"
quick-xml = { version = "0.28", features = ["serialize"] }
serde_json = "1"
serde = { version = "1", features = ["derive", "rc"] }
regex = "1"
toml = "0.7"
async-trait = "0.1.64"
url = "2"
monostate = "0.1"
smol_str = "0.2"
heck = "0.4.1"
mime_guess = "2.0.4"
arc-swap = "1.6.0"
scraper = { version = "0.16", default_features = false }
once_cell = "1.17.1"
ego-tree = "0.6.2"
