[package]
name = "server"
version = "0.1.0"
edition = "2021"
publish = false

[features]
# nightly = ["crc32fast/nightly", "parking_lot/nightly", "hashbrown/nightly"]
brotli = ["sdk/brotli", "reqwest/brotli", "async-compression/brotli", "ftl/brotli"]

[build-dependencies]
built = { version = "0.6", features = ["chrono"] }

[dependencies]
process = { path = "../../bin/process" }

schema = { path = "../schema" }
config = { path = "../config" }

db = { path = "../../crates/db" }
util = { path = "../../crates/util" }
totp = { path = "../../crates/totp" }
framed = { path = "../../crates/framed" }
# processing = { path = "../../crates/processing" }
iplist = { path = "../../crates/iplist" }
blurhash = { path = "../../crates/blurhash" }
task_runner = { path = "../../crates/task_runner" }
filesystem = { path = "../../crates/filesystem" }
z85 = { path = "../../crates/z85" }
emoji = { path = "../../crates/emoji" }
md_utils = { path = "../../crates/md_utils" }

sdk = { git = "https://github.com/Lantern-chat/client-sdk-rs", features = ["pg", "api", "ahash"], package = "client-sdk" }
smol_str = { version = "0.2", features = ["serde", "pg"] }

ftl = { git = "https://github.com/Lantern-chat/ftl", features = ["json", "cbor"] }
mime_db = { git = "https://github.com/Lantern-chat/mime_db" }
thorn = { git = "https://github.com/Lantern-chat/thorn" }
async-chashmap = { git = "https://github.com/novacrazy/async-chashmap" }

timestamp = { package = "iso8601-timestamp", version = "0.2", features = ["pg"] }

serde = { version = "1", features = ["derive", "rc"] }
serde_urlencoded = "0.7"
serde_json = "1.0.64"
bincode = "1"
tokio = { version = "1.4", features = ["full", "parking_lot"] }
tokio-util = { version = "0.7", features = ["io"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-rustls = "0.24.0"
# tls-listener = { version = "0.2.1", features = ["hyper-h1", "hyper-h2", "tokio-net"] }
async-stream = "0.3"
async-trait = "0.1.50"
async-compression = { version = "0.3.8", features = ["deflate", "gzip", "tokio"] }
async-recursion = "1"
hashbrown = { version = "0.13", features = ["inline-more"] }
futures = "0.3"
hyper = { version = "0.14.4", features = ["http1", "http2", "server", "stream", "runtime"] }
tokio-tungstenite = { version = "0.18", default-features = false, features = ["connect"] }
mime = "0.3.16"
http = "0.2.3"
reqwest = { version = "0.11", default-features = false, features = ["gzip", "deflate", "rustls-tls", "json"] }
tracing = { version = "0.1", default-features = false, features = ["log", "std"] }
headers = "0.3"
base64 = "0.21.0"
hex = "0.4.2"
bytes = "1.0.1"
lazy_static = "1.4.0"
# sha3 = "0.9.1"
miniz_oxide = "0.7"
thiserror = "1.0.24"
serde_repr = "0.1.6"
paste = "1.0.5"
ciborium = "0.2"
time = { version = "0.3", features = ["macros"] }
regex = "1.4.6"
regex-automata = "0.1.10"
ahash = "0.8.0"
either = "1.6.0"
failsafe = "1.0.0"
parking_lot = "0.12"
num_cpus = "1.13"
aho-corasick = "1"
arc-swap = "1.2.0"
cache-padded = "1.1.1"
bitflags = "1.2"
pin-project-lite = "0.2.8"
urlencoding = "2.1.0"
# socket2 = "0.5"
anyhow = "1.0.44"
itoa = "1.0.1"
quick-xml = { version = "0.28.0", features = ["serialize"] }
smallvec = "1.7.0"
memchr = "2.4.1"
crc32fast = "1.2.1"
bytecount = "0.6.2"
arrayvec = "0.7.1"
rand = "0.8.3"
base32 = "0.4.0"
aes-gcm-siv = "0.11"
rust-argon2 = "1"
scc = "1.7"
