[package]
name = "totp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.11.0"
base32 = "0.4.0"
sha2 = "0.9.6"

[dev-dependencies]
hex = "0.4.3"