[package]
name = "print_schema"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
thorn = { workspace = true, features = ["generate"] }
tokio = { workspace = true, features = ["full"] }

db.workspace = true

futures.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
argh.workspace = true
