[build]
rustflags = ["-C", "target-feature=+avx2,+aes,+ssse3,+fma", "-C", "target-cpu=native", "-C", "debuginfo=0"] # TODO: Look into exact features needed

[target.x86_64-unknown-linux-gnu.build]
rustflags = ["-C", "target-feature=+avx2,+aes,+ssse3,+fma", "-C", "target-cpu=native", "-C", "debuginfo=1", "-C", "linker-plugin-lto", "-C", "link-arg=-fuse-ld=lld"]
