[package]
name = "nexus"
version = "0.1.0"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2021"
publish = false

[features]
memory_metrics = ["tracking_allocator/enable"]
default = ["memory_metrics"]

[build-dependencies]
built.workspace = true

[dependencies]
sdk = { workspace = true }
rpc.workspace = true
smol_str = { workspace = true, features = ["serde"] }
rkyv = { workspace = true }
postgres-types.workspace = true

quinn.workspace = true
reqwest.workspace = true
headers.workspace = true
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
serde_json = "1"

schema.workspace = true

common.workspace = true
config.workspace = true
framed = { workspace = true, features = ["tokio"] }
task_runner.workspace = true
db.workspace = true
util.workspace = true
process_utils.workspace = true
tracking_allocator.workspace = true
md_utils.workspace = true
mfa_totp.workspace = true
thorn.workspace = true
timestamp.workspace = true
z85.workspace = true

tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
dotenv.workspace = true
anyhow.workspace = true
argh.workspace = true

time = "0.3"
rand = "0.8"
futures = "0.3"
hashbrown.workspace = true
triomphe = "0.1.8"
scc = "2"
ahash = "0.8.0"
arc-swap = "1.2.0"
num_cpus = "1.13"
aes = "0.8"
sha1 = "0.10.5"
hmac = "0.12.1"
thiserror = "1"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
rust-argon2 = "2"
aes-gcm-siv = "0.11"
base32 = "0.5.0"
aho-corasick = "1"
smallvec = "1.11.2"
paste = "1.0.14"
failsafe = "1.2"

[target.'cfg(all(unix, any(target_arch = "x86", target_arch = "x86_64")))'.dependencies]
tikv-jemallocator = { version = "0.6" }

# [target.'cfg(any(target_arch = "x86_64", target_arch = "x86"))'.dependencies]
# server = { path = "../../layers/server", features = ["brotli"] }
