[package]
name = "schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../../crates/util" }

sdk = { git = "https://github.com/Lantern-chat/client-sdk-rs", default-features = false, features = ["pg", "api"], package = "client-sdk" }

thorn = { git = "https://github.com/Lantern-chat/thorn" }

smol_str = "0.1"
serde = { version = "1", features = ["derive"] }
postgres-types = "0.2.1"
# enum_primitive = "0.1.1"
# enum-primitive-derive = "0.2.2"
# num-traits = "0.2"
bitflags = "1.2.1"
aes = "0.7"
time = "0.3"
static_assertions = "1"
rand_core = "0.6"
base64 = "0.13.0"
thiserror = "1"
sha-1 = "0.10"
hmac = "0.12"
byteorder = "1.4"
form_urlencoded = "1"

[dev-dependencies]
serde_json = "1.0.64"
hex = "0.4.3"
criterion = "0.3"

[[bench]]
name = "schema"
harness = false