ALTER TABLE IF EXISTS lantern.party_bans DROP CONSTRAINT IF EXISTS user_fk CASCADE;
ALTER TABLE IF EXISTS lantern.party_bans DROP CONSTRAINT IF EXISTS party_fk CASCADE;

DROP TABLE IF EXISTS party_bans CASCADE;