DROP INDEX IF EXISTS user_block_user_idx CASCADE;

ALTER TABLE IF EXISTS lantern.user_blocks DROP CONSTRAINT IF EXISTS user_fk CASCADE;
ALTER TABLE IF EXISTS lantern.user_blocks DROP CONSTRAINT IF EXISTS block_fk CASCADE;

DROP TABLE IF EXISTS user_blocks CASCADE;