[package]
name = "main"
version = "0.1.0"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# nightly = ["web/nightly"]
# armv8 = ["nightly", "web/armv8"]
memory_metrics = ["tikv-jemallocator"]
default = ["memory_metrics"]

[dependencies]
server = { path = "../../layers/server" }

task_runner = { path = "../../crates/task_runner" }
db = { path = "../../crates/db" }
util = { path = "../../crates/util" }

tokio = { version = "1", features = ["full", "parking_lot"] }
futures = "0.3"
tracing = { version = "0.1", default-features = false, features = ["log", "std"] }
tracing-futures = { version = "0.2.4", default-features = false, features = ["std-future"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "parking_lot", "registry"] }
tracing-appender = { version = "0.2", features = ["parking_lot"] }
dotenv = "0.15.0"
anyhow = "1"
pico-args = "0.5.0"

[target.'cfg(all(unix, any(target_arch = "x86", target_arch = "x86_64")))'.dependencies]
tikv-jemallocator = { version = "0.5", optional = true }

[target.'cfg(any(target_arch = "x86_64", target_arch = "x86"))'.dependencies]
server = { path = "../../layers/server", features = ["brotli"] }