[package]
name = "gateway"
version = "0.1.0"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2021"
publish = false

[features]
memory_metrics = []
brotli = ["sdk/brotli", "reqwest/brotli", "async-compression/brotli", "ftl/brotli"]
default = ["memory_metrics", "brotli"]

[build-dependencies]
built.workspace = true

[dependencies]
sdk = { workspace = true, features = ["driver", "cbor"] }
rpc.workspace = true
rkyv.workspace = true
smol_str = { version = "0.2", features = ["serde", "pg"] }

quinn.workspace = true
tokio = { workspace = true, features = ["full"] }
serde.workspace = true

ftl.workspace = true
async-compression = { version = "0.4", features = ["deflate", "gzip", "tokio"] }
reqwest = { version = "0.11", default-features = false, features = ["gzip", "deflate", "rustls-tls", "json"] }
hyper = { version = "1", features = ["http1", "http2", "server"] }
hyper-util = { version = "0.1.2", features = ["tokio"] }
http-body-util = "0.1.0"
tokio-tungstenite = { version = "0.21", default-features = false, features = ["connect"] }
http.workspace = true
headers.workspace = true

schema.workspace = true

common.workspace = true
config.workspace = true
task_runner.workspace = true
db.workspace = true
util.workspace = true
process_utils.workspace = true
tracking_allocator.workspace = true
z85.workspace = true

futures.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
dotenv.workspace = true
anyhow.workspace = true
argh.workspace = true

hashbrown.workspace = true
triomphe = "0.1.8"
aho-corasick = "1"
scc = "2"
ahash = "0.8.0"
arc-swap = "1.2.0"
num_cpus = "1.13"
aes = "0.8"
sha1 = "0.10.5"
hmac = "0.12.1"
thiserror = "1"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
lazy_static = "1"
nohash-hasher = "0.2.0"
async-trait = "0.1"
serde_json = "1.0.108"
ciborium = "0.2.1"
quick-xml = "0.31.0"
serde_urlencoded = "0.7.1"
base64 = "0.21.5"
mime = "0.3.17"
bytes = "1.5.0"
urlencoding = "2.1.3"
async-recursion = "1"


[target.'cfg(all(unix, any(target_arch = "x86", target_arch = "x86_64")))'.dependencies]
tikv-jemallocator = { version = "0.5" }
